---
title: Resources for Network Analysis
...

## Sample data sets

[China Dimensions data collection](http://sedac.ciesin.org/data/collection/cddc)

[Stanford Large Network Dataset Collection](https://snap.stanford.edu/data/)

[Gephi datasets](https://github.com/gephi/gephi/wiki/Datasets)

Lincoln Mullen, [historydata: Datasets for Historians](https://github.com/ropensci/historydata)

## Data repositories

[Datahub](http://datahub.io/).

[Data.gov](http://www.data.gov/)

[Data.gov.uk](http://data.gov.uk/)

## Tutorials

Marten Düring, "[From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources](http://programminghistorian.org/lessons/creating-network-diagrams-from-historical-sources)"

Martin Grandjean, "[Introduction to Network Analysis and Visualization](http://www.martingrandjean.ch/gephi-introduction/)"

Miriam Posner, [Cytoscape tutorials](https://github.com/miriamposner/cytoscape_tutorials)

Brian Sarnacki, [The Complete n00b’s Guide to Gephi](http://www.briansarnacki.com/gephi-tutorial/)

## Writing on networks

Peter Bearman, James Moody, and Robert Faris, "Networks and History" *Complexity* 8 (2012): 61–71.

Shawn Graham, Ian Milligan, and Scott Weingart, *The Historian's Macroscope: Big Digital History* (Imperial College Press, 2016). See especially [Network Analysis](http://www.themacroscope.org/?page_id=889) and [Network Analysis Fundamentals](http://www.themacroscope.org/?page_id=892).

Kieran Healy, "[Using Metadata to Find Paul Revere](https://kieranhealy.org/blog/archives/2013/06/09/using-metadata-to-find-paul-revere/") (June 9, 2013)

Claire Lemercier, "[Formal network methods in history: why and how?](https://hal.archives-ouvertes.fr/file/index/docid/649316/filename/lemercier_A_zg.pdf)"

Manuel Lima, *[The Book of Trees: Visualizing Branches of Knowledge](http://www.bookoftrees.info/bt/)* (Princeton Architectural Press, 2013).

Franco Moretti, *[Graphs, Maps, and Trees: Abstract Models for Literary History](https://www.versobooks.com/books/261-graphs-maps-trees)* (Verso, 2005).

Scott Weingart's series on "[Networks Demystified](http://scottbot.net/tag/networks-demystified/)".

The [Historical Network Research bibliography](http://historicalnetworkresearch.org/resources/bibliography/).

# Digital projects

- Micki Kaufman, ["Everything on Paper Will Be Used Against Me": Quantifying Kissinger](http://blog.quantifyingkissinger.com/)
- [Mapping the Republic of Letters](http://republicofletters.stanford.edu/)
- [Viral Texts: Mapping Networks of Reprinting in 19th-Century Newspapers and Magazines](http://viraltexts.org/)
- Rebecca Wingo, "[Homestead Nebraska](http://homestead.unl.edu/projects/homesteading-the-plains/)"
- Brian Sarnacki, "[The Corrupt Network](http://www.briansarnacki.com/the_corrupt_network/)"
- [ORBIS](http://orbis.stanford.edu/)
- Andy Wilson, [Mapping the Revolution](https://andrewwilson84.wordpress.com/2016/03/07/mapping-the-revolution/)
- [O San Can You See: Early Washington D.C. Law & Family](http://earlywashingtondc.org/)
- [Network of Thrones](https://www.macalester.edu/~abeverid/thrones.html)
- [Kindred Britain](http://kindred.stanford.edu/)
- [How every #GameOfThrones episode has been discussed on Twitter](https://interactive.twitter.com/game-of-thrones/#?episode=60)
- [Network visualization: mapping Shakespeare’s tragedies](http://www.martingrandjean.ch/network-visualization-shakespeare/)
- [Star Trek character network](https://datascopeanalytics.com/startrekviz/)